version: "3.3"

services:

  traefik:
    image: "traefik:v2.3"
    networks:
      - backendsiren
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.postgrest.address=:3000"
    ports:
      - "3034:80"
      - "3000:3000"
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
    backendsiren:
        driver: bridge
